[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["naoketa <49198895+naoketa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
